version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: Filip
      POSTGRES_PASSWORD: password
    networks:
      - postgres
    volumes:
      - postgres:/data/postgres

  postgres_test:
    container_name: postgres_test
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin

  spring-react-app:
    image: xmlynek/spring-react-fullstack-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
