name: CI

on:
  pull_request:
    branches:
      - master

env:
  JAVA_VERSION: 17.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'openjdk'
      - name: Mvn clean package
        run: mvn --batch-mode --update-snapshots --no-transfer-progress clean package -P build-frontend

